name: UnityCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    #container: ppartida/unity-ci:v2019.4.24f1-01
    container: ppartida/unity-ci:latest
    steps:
      # Checkout
      - uses: actions/checkout@v2

      # Activate the license inside your .github project
      # Replace this with your own license handling
      - name: License activation
        run: /opt/unity/Editor/Unity -quit -batchmode -nographics -force-free -manualLicenseFile .github/Unity_v2019.x.ulf || exit 0

      - name: Create Test Results dir
        run: mkdir /opt/TestResults

      - name: Create Default UnityLog file
        run: touch /opt/TestResults/UnityLog.txt

      - name: Create Default TestResults.xml file
        run: touch /opt/TestResults/TestResults.xml

      # Run Tests
      - name: EditMode - Unit Testing
        run: xvfb-run -a --server-args="-screen 0 1024x768x24" /opt/unity/Editor/Unity -runTests -nographics -batchmode -projectPath . -testResults /opt/TestResults/TestResults.xml -testPlatform EditMode || exit 0

      # ls Current test results
      - name: List test results (most likely run a script that parses this
        run: ls /opt/TestResults/

      # Print TestResults.xml
      - name: List test results (most likely run a script that parses this
        run: cat /opt/TestResults/TestResults.xml

        # Parse TestResults to JSON/HTML
        # Move to directory because the script looks up for Template in the same path 
      - name: Parse Test Results
        run: cd /UnityTestRunnerResultsReporter/bin/Release/net5.0/ && dotnet UnityTestRunnerResultsReporter.dll --resultsPath=/opt/TestResults/

      # ls TestResults after json and html are created
      - name: List test results (most likely run a script that parses this
        run: ls /opt/TestResults/

      - uses: actions/upload-artifact@v2
        with:
          name: Upload test results
          path: |
            /tmp/TestResults
            !/tmp/TestResults