name: UnityCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2019.4.24f1-android-0.11.0
    steps:
      # Checkout
      - uses: actions/checkout@v2
      
      # Activate the license inside your .github project
      # Replace this with your own license handling
      - name: License activation
        run: /opt/unity/Editor/Unity -quit -batchmode -nographics -force-free -manualLicenseFile .github/Unity_v2019.x.ulf || exit 0
      
      # Run Tests
      - name: EditMode - Unit Testing
        run: /opt/unity/Editor/Unity -runTests -nographics -batchmode -projectPath . -testResults "/tmp/TestResults" -testPlatform EditMode || exit 0
      
      # Print TestResults.xml
      - name: List test results (most likely run a script that parses this
        run: cat "/tmp/TestResults.xml"

      # Parse TestResults to JSON/HTML
      - name: EditMode - Unit Testing
        run: /opt/unity/Editor/Unity -runTests -nographics -batchmode -projectPath . -testResults "/tmp/TestResults" -testPlatform EditMode || exit 0